name: Go

on:
  push:
    branches: [main]
    paths: 
      - '**.go'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.19.9
      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.0
      - name: Run golangci-lint
        run: golangci-lint run ./...
  test:
      needs: lint
      runs-on: ubuntu-latest
      steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.19.9
      - name: Go Test
        run: go test -v ./...
          
